FROM node:12.13.1-alpine3.9

WORKDIR /app

ARG FONTAWESOME_NPM_AUTH_TOKEN

COPY ./package.json ./

RUN npm config set @fortawesome:registry https://npm.fontawesome.com/
RUN npm config set "//npm.fontawesome.com/:_authToken"  ${FONTAWESOME_NPM_AUTH_TOKEN}

RUN npm install

COPY . .

CMD ["npm", "run", "serve"]